# Generated by Django 5.1.15 on 2026-07-15 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="due_at",
            field=models.DateTimeField(
                blank=True, help_text="When the current checkout is due back", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("serialized", "Serialized (tracked individually)"),
                    ("consumable", "Consumable (tracked by quantity)"),
                ],
                default="serialized",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="min_quantity",
            field=models.IntegerField(
                default=0,
                help_text="Reorder point; low stock at or below this (consumables)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="quantity",
            field=models.IntegerField(
                default=1, help_text="On-hand quantity (consumables)"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="quantity_delta",
            field=models.IntegerField(
                blank=True, help_text="Consumable change (+restock / -issue)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="job_ref",
            field=models.CharField(
                blank=True,
                help_text="Free-text job note (legacy / when no Job record)",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tag",
            name="uid",
            field=models.CharField(
                help_text="NFC chip UID or encoded payload", max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("assign", "Assign"),
                    ("confirm_checkout", "Confirm checkout"),
                    ("confirm_return", "Confirm return"),
                    ("accept_return", "Accept return"),
                    ("to_maintenance", "Send to maintenance"),
                    ("mark_lost", "Mark lost"),
                    ("issue", "Issue (consumable)"),
                    ("restock", "Restock (consumable)"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tx_counterparty",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Available"),
                    ("assigned", "Assigned"),
                    ("checked_out", "Checked out"),
                    ("in_transit", "In transit"),
                    ("returned_pending", "Returned, pending inspection"),
                    ("maintenance", "In maintenance"),
                    ("lost", "Lost"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="transactionphoto",
            name="sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Job/project code, e.g. JOB-42",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "site",
                    models.CharField(
                        blank=True, help_text="Jobsite / location", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "foreman",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-status", "code"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="inventory.job",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="inventory.job",
            ),
        ),
    ]
