# Generated by Django 5.1.15 on 2026-07-14 18:10

import django.db.models.deletion
import inventory.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Human-readable asset ID, also printed on the label",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("checked_out", "Checked out"),
                            ("in_transit", "In transit"),
                            ("returned_pending", "Returned, pending inspection"),
                            ("maintenance", "In maintenance"),
                            ("lost", "Lost"),
                        ],
                        default="available",
                        max_length=32,
                    ),
                ),
                (
                    "job_ref",
                    models.CharField(
                        blank=True,
                        help_text="Current job/project the asset is out on",
                        max_length=120,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="assets/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="held_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("nfc", "NFC"),
                            ("qr", "QR code"),
                            ("barcode", "Barcode"),
                        ],
                        default="nfc",
                        max_length=16,
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        help_text="NFC chip UID, or the payload printed/encoded on the tag (URL, code)",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="Tag has been write-locked in the field",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="inventory.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("assign", "Assign"),
                            ("confirm_checkout", "Confirm checkout"),
                            ("confirm_return", "Confirm return"),
                            ("accept_return", "Accept return"),
                            ("to_maintenance", "Send to maintenance"),
                            ("mark_lost", "Mark lost"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("checked_out", "Checked out"),
                            ("in_transit", "In transit"),
                            ("returned_pending", "Returned, pending inspection"),
                            ("maintenance", "In maintenance"),
                            ("lost", "Lost"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("checked_out", "Checked out"),
                            ("in_transit", "In transit"),
                            ("returned_pending", "Returned, pending inspection"),
                            ("maintenance", "In maintenance"),
                            ("lost", "Lost"),
                        ],
                        max_length=32,
                    ),
                ),
                ("job_ref", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("client_uuid", models.UUIDField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tx_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.asset",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        help_text="The other party in a two-factor handoff",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tx_counterparty",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=inventory.models.photo_upload_path),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the image bytes for tamper-evidence",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="inventory.transaction",
                    ),
                ),
            ],
        ),
    ]
